-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 18:21:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deadstrike
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `deadstrike` DEFAULT CHARACTER SET utf8 ;
USE `deadstrike` ;

-- -----------------------------------------------------
-- Table `deadstrike`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deadstrike`.`jugador` ;

CREATE TABLE IF NOT EXISTS `deadstrike`.`jugador` (
  `idjugador` INT NOT NULL AUTO_INCREMENT,
  `nick_name` VARCHAR(45) NOT NULL,
  `ultimo_nivel` VARCHAR(45) NOT NULL,
  `puntaje_actual` INT NOT NULL,
  PRIMARY KEY (`idjugador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deadstrike`.`niveles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deadstrike`.`niveles` ;

CREATE TABLE IF NOT EXISTS `deadstrike`.`niveles` (
  `idnivel` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `nombre_nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deadstrike`.`partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deadstrike`.`partida` ;

CREATE TABLE IF NOT EXISTS `deadstrike`.`partida` (
  `niveles_idnivel` INT NOT NULL,
  `jugador_idjugador` INT NOT NULL,
  `tiempo_jugador` TIME NOT NULL,
  `items` ENUM('patines', 'barril') NOT NULL,
  `vidas_rest` INT NOT NULL,
  `puntaje_final` INT NOT NULL,
  `bonus` INT NOT NULL,
  `id_partida` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`niveles_idnivel`, `jugador_idjugador`),
  INDEX `fk_niveles_has_jugador_jugador1_idx` (`jugador_idjugador` ASC) VISIBLE,
  INDEX `fk_niveles_has_jugador_niveles1_idx` (`niveles_idnivel` ASC) VISIBLE,
  CONSTRAINT `fk_niveles_has_jugador_niveles1`
    FOREIGN KEY (`niveles_idnivel`)
    REFERENCES `deadstrike`.`niveles` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_niveles_has_jugador_jugador1`
    FOREIGN KEY (`jugador_idjugador`)
    REFERENCES `deadstrike`.`jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deadstrike`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deadstrike`.`usuario` ;

CREATE TABLE IF NOT EXISTS `deadstrike`.`usuario` (
  `nombre` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idjugador` INT NOT NULL,
  `registro` DATETIME NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_jugador1_idx` (`idjugador` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_jugador1`
    FOREIGN KEY (`idjugador`)
    REFERENCES `deadstrike`.`jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
